config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'  #pages =controller, about =action
  get 'signup', to:'users#new'
  resources :users, except: [:new] #all the routes except the new one
  resources :articles  #gives us a new article path, a post to create and edit, delete, show, index,
                       # and update article
  get 'login', to: 'sessions#new' #sessions=controller, new=action
  post 'login', to: 'sessions#create' #will post the form and create user's session (logged in state)
  delete 'logout', to: 'sessions#destroy' #user logout, destroy session

  resources :categories, except: [:destroy]  #we don't want a delete action for categories

# Resource routing allows you to quickly declare all of the common routes for a given resourceful controller.
# Instead of declaring separate routes for your index , show , new , edit , create , update and destroy actions,
#a resourceful route declares them in a single line of code.

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  # Here we define all the constraints for the atrributes title and description that will show in the error messages

  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true   #any time an article is created, it ensures that user_id is present

end

app/controllers/articles_controller.rb
class ArticlesController <ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy] #call the set article method before these mentioned methods
  before_action :require_user, except:  [:index, :show] #all the other methods require a logged in user
  before_action :require_same_user, only: [:edit, :update, :destroy] #only user who created the article can operate these actions

def index
#@articles= Article.all    grab all articles in db
@articles = Article.paginate(page: params[:page], per_page: 5) #add pagination-loads the set no.of articles per page -here 5
end

 def new
   @article =Article.new  #initiate the article variable, which will create a form at the UI level
 end                      #Article = class name(model) - we create an object (@article) for this class

 def create
 @article=Article.new(article_params) #To whitelist the values of article, we must create the method article_params
 @article.user = current_user  #the article is assigned to the actual current user
   if @article.save
   flash[:success]= "Article was successfully created"  #:success is the name of message (Boot); will display in application
   redirect_to article_path(@article)  #the index of the actions
   else
   render "new"    #if article is not saved, render the ‘new article’ template
   end
end

def  show

  end

def destroy

  @article.destroy   #delete the article
   flash[:danger] = "Article was successfully deleted"
   redirect_to articles_path
end

def edit
@article = Article.find(params[:id])
end

def update

if @article.update(article_params)
flash[:success]= "Article was successfully updated"
redirect_to article_path(@article)
else
render "edit"
end
end



#we create the validating method that we call above in Article.new
private
def set_article
  @article = Article.find(params[:id])   #find an article from its ID
end

def article_params
# :article = top-level key  which will permit the value of title and description
params.require(:article).permit(:title, :description, category_ids: []) # [] = category_ids come in array form
#require and permit are 2 predefined rails method
end   #params come from the users' browser when they request the page(in rails they are a hash with hashes inside)

def require_same_user  #only user who created an article can edit/delete it

if current_user != @article.user and !current_user.admin?

flash[:danger] = "You can only edit or delete your own articles"

redirect_to root_path

end

end

end

app/views/articles/_article.html.erb
<!--to display all articles, we iterate to @articles instance variable (that has all the articles from db)-->

<!-- @articles includes all the articles; article= each individual item -->


<% obj.each do |article| %> <!-- obj = generic object for different instances(@article, etc) -->

<div class="row">

<div class="col-xs-8 col-xs-offset-2">

<div class="well well-lg">

<div class="article-title">

<%= link_to article.title, article_path(article) %>

</div>

<div class="article-body">

<%= truncate(article.description, length: 100) %>

<div class="article-meta-details">

<small>Created by: <%= article.user.username if article.user%>,

<%= time_ago_in_words(article.created_at) %> ago,

last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>

</div>

</div>

<!--display the article category-->

<% if article.categories.any? %>
<p>Categories: <%= render article.categories %></p>
<% end %>

<!--ADMIN- only if it's the user who created the article, can access the actions -->
<% if logged_in? && (current_user == article.user || current_user.admin?) %>

<div class="article-actions">

<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>

<%= link_to "Delete this article", article_path(article), method: :delete,

data: { confirm: "Are you sure you want to delete the article?"},

class: "btn btn-xs btn-danger" %>

</div>
<% end %>

</div>

</div>

</div>

<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<!-- full_messages() public
Returns all the full error messages in an array -->

<!-- In article.rb we defined all the constraints for the title and description that will show in the error messages-->


  <div class ='row'>
     <div class ='col-xs-10'>
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>

  <!-- TITLE-->
  <div class="form-group"> <!--Bootstrap class for the a form group-->
    <div class= "control-label col-sm-2"> <!-- title label-->
  <%= f.label :title %>
  </div>
  <div class="col-sm-10" > <!-- title input-->
  <%= f.text_field :title, class: "form-control", placeholder:"Title of article", autofocus: true %>
   </div>  <!-- end of title input-->
  </div> <!-- end of title group-->

<!-- DESCRIPTION-->
 <div class="form-group"> <!--Bootstrap class for a form group-->
    <div class= "col-sm-2 control-label"> <!-- description label-->
  <%= f.label :description %>
     </div> <!-- end of description label-->
  <div class=" col-sm-10" > <!-- description input-->
  <%= f.text_area :description, rows: 10,  class: "form-control", id: "body-article", placeholder:"Body of article" %>
  </div>
 </div> <!-- end of description group-->

<!-- the category associated with the article-->
<div class="form-group">
 <div class="row">
  <div class="col-sm-offset-2 col-sm-8">
   <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
   <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
   <%end %>
</div>
</div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10 bt-article">
  <%= f.submit class: 'btn btn-primary btn-lg' %>
  </div>
</div>
  <% end %>
  <div class="col-sm-offset-2 col-sm-10 center">
    <%= link_to "Cancel and return to articles listing", articles_path  %>
  </div>
   </div>
  </div>

app/views/articles/edit.html.erb
<h1 class="center bottom-space">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="center">Listing all articles</h1>

<!-- add a display for the pagination -->
<div align="center">
<%= will_paginate %> <!--pagination library -->
</div>

<%= render 'article', obj: @articles %> <!-- we assign the value for obj: @articles -->
<div align="center">
<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 class="center bottom-space"> Create an article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="center">Title: <%= @article.title %> </h2>
 <div class= "well col-xs-8 col-xs-offset-2">

   <% if @article.user %>  <!--if the article has a user -->
   <ul class="listing">
   <div class="row center">
   <div class="col-md-4 col-md-offset-4">
   <li>Created by:</li>
   <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
   <li class="article-title">
   <%= link_to @article.user.username, user_path(@article.user) %>
   </li>
   <li><small>
   <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
   <!--if @article.user.articles = if the user who wrote this particular article has more articles -->
   </small></li>
   </div>
   </div>
   </ul>
   <% end %>

   <h3 class="center description"><strong>Description:</strong>
    <hr>
    <%= simple_format(@article.description) %></h3> <!--simple_format -displays the original format of description -->

<!--display the category for  the article -->
    <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p> <!--exactly like each, this will loop through the cat array -->
    <% end %>

 <div class="article-actions center">

<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> <!-- we use var @article , to get the article from ID -->
<%= link_to "Delete this article", article_path(@article), class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this article? "} %>
<% end %>
<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>

  </div>
  </div>