config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'  #pages =controller, about =action
  get 'signup', to:'users#new'
  resources :users, except: [:new] #all the routes except the new one
  resources :articles  #gives us a new article path, a post to create and edit, delete, show, index,
                       # and update article
  get 'login', to: 'sessions#new' #sessions=controller, new=action
  post 'login', to: 'sessions#create' #will post the form and create user's session (logged in state)
  delete 'logout', to: 'sessions#destroy' #user logout, destroy session

  resources :categories, except: [:destroy]  #we don't want a delete action for categories

# Resource routing allows you to quickly declare all of the common routes for a given resourceful controller.
# Instead of declaring separate routes for your index , show , new , edit , create , update and destroy actions,
#a resourceful route declares them in a single line of code.

end

app/views/layouts/_footer.html.erb
<div class="container-full">
<footer class="footer">

<small class="center">

Copyright © <a href="http://monicalauraburns.blogspot.com">The Blog of Monica Laura</a>

by <a href="http://www.monica-laura.com/">Monica Laura</a>

</small>

<nav>

<ul>

<li><%= link_to "About", about_path %></li>

</ul>

</nav>

</footer>


  </div> <!--end of full container -->

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-4, col-xs-offset-4">
<% flash.each do | name, msg| %>  <!--loop through messages created in controller -->
<div class= 'alert alert-<%="#{name}" %>'>
  <!-- name stands for the type of the message'success', or 'danger'(alert-succes) , taken by
looping through messages created in controller:  flash.each do | name, msg| -->

  <a href="#" class="close" data-dismiss="alert">&#215;</a>
  <!-- content_tag: Returns an HTML block tag of type name surrounding the content. -->
  <!--This line is calling the "content_tag" view helper, which will render a string of HTML which will look like this
<div id="flash_error">this is a message</div>  -->
<!--if the variable name  has a value of error  and the variable msg  is a string and has the value this is a message
If msg  is not a string, nothing will be rendered.-->

  <%= content_tag :div, msg, :id => "flash_#{name}" if msg. is_a?(String)%>
  </div>
<% end %>
 </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "Articles", articles_path %></li>

        <li><%=link_to "Users", users_path %></li>
        <!--categories display -->
        <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
      <ul class="dropdown-menu">
      <li><%= link_to "All Categories", categories_path %></li>
      <!--display each category's name in the dropdown menu -->
      <% Category.all.each do |category| %>
      <li><%= link_to "#{category.name}", category_path(category) %></li>
      <% end %>
      <!--categories actions with admin restrictions -->
      <% if logged_in? and current_user.admin? %>   <!--if it's logged in user AND admin -->
      <li role="separator" class="divider"></li>
      <li><%= link_to "Create New Category", new_category_path %></li>
      <% end %>
      </ul>
      </li>
    <!--display User Profile -->
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
            <li><%=link_to "Log out", logout_path, method: :delete %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
                <li><%= link_to "View your profile", user_path(current_user) %></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
            <% else %>
                <li><%= link_to 'Log in', login_path %></li>
                <li><%= link_to 'Sign up', signup_path %></li>

            <% end %>


        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %> <!--we need to give the layouts folder, because application looks by default in the articles folder templates -->
    <div class= "container-full">
    <%= yield %>  <!-- this serves every page  -->
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>